### ISSUE TITLE
MB - scroll-zoom in v1 browser

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packtau#1]
Hi Ben, 
i know this module is just experimental and might dissapear at some point.
But for now it would be nice if i could zoom in and out with the notebook touchpad.
Not sure if this is already possible? On Windows 10 i can not zoom with a mousepad.

**Comment by stoermelder** [comment]
Do you mean in the module browser?

**Comment by Eurikon** [comment]
Yes that is correct.

**Comment by stoermelder** [comment]
I've added this right now. But make now mistake, it is not working very smoothly because of how the previews are generated.

**Comment by Eurikon** [comment]
Thanks, ok understood!

**Comment by Eurikon** [comment]
Was this already added to the nightly build:
Mon Aug 10 21:15:00 UTC 2020

If so, i was not able to zoom with mousepad/touchpad yet.

**Comment by stoermelder** [comment]
Yes. It does work on Windows here, not sure about other OS how the touchpad is handled though. You can try Ctrl+Mousewheel which works the same way.

**Comment by Eurikon** [comment]
Just to be more clear, i am not talking about scroll zoom, or ctrl + gesture zoom.
I meant multi touch zoom, pinch zoom (two finger zoom). 
This is working in VCV Rack itself, but not in your modded browser :) 
(for me on my computer here, Windows 10)

**Comment by stoermelder** [comment]
Yes, works here. Does Ctrl+Mousewheel work? It is the same command as „two finger zoom“.

**Comment by Eurikon** [comment]
Hi Ben, i had to find a mouse first :) 

With ctrl + mouse  scroll i get no zoom here.
I do get zoom inside VCV Rack with ctrl + mouse scroll and/or 2 finger pinch.

**Comment by stoermelder** [comment]
That is strange. I added a slider in top right corner of the browser yesterday. Can you check if this works?

**Comment by Eurikon** [comment]
I just checked the latest build, everything works fine now! 
Thanks for this Ben :)

**Comment by stoermelder** [comment]
Nice!
