### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packtau#10]
[4.632 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
12: ./Rack(+0x1f63b5) [0x55b99a1a53b5]
11: /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f676a98e040]
10: ./Rack(_ZN4rack6widget6Widget8addChildEPS1_+0x5a) [0x55b99a1f00f6]
9: /home/ewen/.Rack/plugins-v1/Stoermelder-PackTau/plugin.so(_ZN2Mb14BrowserOverlayD1Ev+0xdc) [0x7f673422d9c6]
8: /home/ewen/.Rack/plugins-v1/Stoermelder-PackTau/plugin.so(_ZN2Mb14BrowserOverlayD0Ev+0x9) [0x7f673422d9f1]
7: ./Rack(_ZN4rack6widget6Widget13clearChildrenEv+0x132) [0x55b99a1f04a6]
6: ./Rack(_ZN4rack6widget6WidgetD1Ev+0x1f) [0x55b99a1f04d5]
5: ./Rack(_ZN4rack3app5SceneD0Ev+0x35) [0x55b99a1e3fed]
4: ./Rack(_ZN4rack3AppD1Ev+0x18) [0x55b99a1a5994]
3: ./Rack(_ZN4rack10appDestroyEv+0x15) [0x55b99a1a5a5e]
2: ./Rack(main+0x595) [0x55b99a1159b5]
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f676a970bf7]
0: ./Rack(_start+0x2a) [0x55b99a11a89a]

Linux.  Also, MB switch to most used often only updates the first few modules in the browser, eventually my most used will show again, but not managed to identify what may cause this, figured it might be related to that above.

Thanks as always for your great work.

**Comment by stoermelder** [comment]
You can’t use PackTau and MB the same time, sorry, so please uninstall PackTau or don’t use MB.
