### ISSUE TITLE
Module Mb missing/disabled

### ISSUE THREAD

**Issue by SteveRussell33** [stoermelder/vcvrack-packtau#11]
I rebuilt the plugin for the latest SDK v2.git.219bbaf1 and the module Mb doesn't appear in the browser.

I use this module as I prefer the v1 browser. Would you consider re-enabling this please?

Thanks.

**Comment by stoermelder** [comment]
I moved this module over to PackOne some time ago and it available there.

**Comment by SteveRussell33** [comment]
Ah OK hadn't noticed. Thanks.
