### ISSUE TITLE
MB v2?

### ISSUE THREAD

**Issue by ThePython10110** [stoermelder/vcvrack-packtau#12]
I don't like the new module browser. Everything is a dropdown, meaning an extra click or two to do what I want. MB doesn't appear to be included in PackTau v2 (Windows 10, in case you're wondering), and I would like it to be. I guess you would need to add room brightness if you were going to do it...

**Comment by pgatt** [comment]
It's now a part of PackOne.

**Comment by ThePython10110** [comment]
Unfortunately, `string::fuzzyScore` is *not* in v2.0.0, which means that I can't use it.

**Comment by stoermelder** [comment]
MB was moved to "PackOne" some time ago. While PackOne is not yet available in the VCV Library you can download automated development builds for your OS or build it yourself, including MB for v2.
