### ISSUE TITLE
Trouble building v1.

### ISSUE THREAD

**Issue by TheGuyWhoo** [stoermelder/vcvrack-packtau#18]
Hello! I am very sorry to bother you without outdated matters. My gpu is quite old, so unfortunately I can only use Rack 1 and cardinal. I am very interested in RF module, however when I try to build packtau v1 with sdk 1.1.6 for rack 1.1.6, using msys on windows, I am met with this error:

      In file included from src/MenuBarEx.cpp:3:
      src/mb/Mb.hpp:11:39: error: 'numeric_limits' is not a member of 'std'
         11 |         int64_t usedTimestamp = -std::numeric_limits<int64_t>::infinity();
            |                                       ^~~~~~~~~~~~~~
      src/mb/Mb.hpp:11:61: error: expected primary-expression before '>' token
         11 |         int64_t usedTimestamp = -std::numeric_limits<int64_t>::infinity();
            |                                                             ^
      src/mb/Mb.hpp:11:64: error: '::infinity' has not been declared
         11 |         int64_t usedTimestamp = -std::numeric_limits<int64_t>::infinity();
            |                                                                ^~~~~~~~
      make: *** [../../compile.mk:69: build/src/MenuBarEx.cpp.o] Error 1

Again I know this is deprecated, but am hoping you can help me anyways. Perhaps you have some old builds of v1 kicking around?

**Comment by stoermelder** [comment]
Try this one which I had on my hard drive.
[Stoermelder-PackTau-1.0.0-dev-win.zip](https://github.com/stoermelder/vcvrack-packtau/files/14808059/Stoermelder-PackTau-1.0.0-dev-win.zip)

**Comment by TheGuyWhoo** [comment]
Thank you! That works, however rf is not included in that version.

**Comment by stoermelder** [comment]
Ok, I got the same error comiling the old version. Adding 
`#include <limits>`
to plugin.hpp solves that problem if you want to compile it yourself.
[Stoermelder-PackTau-1.0.0-dev-win.zip](https://github.com/stoermelder/vcvrack-packtau/files/14808304/Stoermelder-PackTau-1.0.0-dev-win.zip)

**Comment by TheGuyWhoo** [comment]
That works, thanks a ton!

**Comment by Cardinny** [comment]
I happened across this and manage to build it successfully, however the inclusion of rf causes code 127:

    [0.351 warn src/plugin.cpp:158] Could not load plugin C:\Users\card\DOCUME~1/Rack/plugins-v1/Stoermelder-PackTau: Failed to load library C:\Users\nick\DOCUME~1/Rack/plugins-v1/Stoermelder-PackTau/plugin.dll: code 127

When I take out rf and build packtau, it loads fine. Any idea what I can do to solve this?
