### ISSUE TITLE
Mb - incorrect focus in v0.6 browser

### ISSUE THREAD

**Issue by pgatt** [stoermelder/vcvrack-packtau#2]
Don't know if the regular module browser had this issue but vague memory tells me it didn't.

I have your 0.6 module browser module in the rack - and when I press enter to bring it up and then either select a module or press escape to jump out of the module it seems like Rack loses key focus. For example if I then press delete while hovering over a module the module doesn't get deleted or if I press enter to go back into the module browser it doesn't come up. I have to click on rack with the mouse and then the keyboard resumes working. Let me know if you need more info.

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
