### ISSUE TITLE
MB  Favorite / hide fonction 

### ISSUE THREAD

**Issue by Motopomp** [stoermelder/vcvrack-packtau#4]
Hello, I use, or rather I test the MB module and for the moment everything is going well.
But several questions come to me.
How do the "favorite" and "hidden" functions work?
How can I no longer hide a module, or there is a list, the same for the favorite, I can choose them, but I do not know how to see them and therefore modify my selection.
Is this a bug?

**Comment by Motopomp** [comment]
I also say to myself, what can be, there is no need to solve this problem if it is one, because the functions will be integrated directly in version 2 of VCV and therefore this module will no longer be necessary

**Comment by stoermelder** [comment]
You can toggle hidden modules with Ctrl+Space back in.
At the moment it is pure speculation when Rack v2 will be released and what features it will include.
