### ISSUE TITLE
[MB] Ctrl hook issue?

### ISSUE THREAD

**Issue by dowodenum** [stoermelder/vcvrack-packtau#5]
Hi stoermelder,

Love this pack. MB feels like it should be part of VCV.

The only thing I wish was different about it is the fact that it hooks Ctrl to the point where I can't Ctrl+A to select (and then delete) what's in the search box.

It's not a huge deal, it's just so ingrained in me as a habit that I stumble every time now. Maybe there's a way to make the Ctrl hook only work if the mouse is hovering over a module?

Anyway, thanks for all your efforts, whether you decide to address this or not.

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
