### ISSUE TITLE
How to use Exit?

### ISSUE THREAD

**Issue by jamshark70** [stoermelder/vcvrack-packtau#8]
Exit was recommended to me, as I was looking for a way to quit Rack programmatically.

It doesn't seem to do this...? Either I've misunderstood the purpose, or I'm not feeding in the right trigger signal, or the module doesn't work in Linux. Entirely unclear to me.

Thanks for any advice.

**Comment by stoermelder** [comment]
EXIT has another purpose right now: it allows you to load another patch triggered by CV and creating some sort of a „interlinked“ playlist of patches. Currently there is no option to exit Rack completely but I can investigate as this might fit in the scope of the module.

**Comment by jamshark70** [comment]
Understood, thanks.

**Comment by stoermelder** [comment]
Trigger-input for "Quit" added in the latest commit.

**Comment by jamshark70** [comment]
Wow! That was fast. Thanks!

**Comment by jamshark70** [comment]
FYI, finally had a chance to try it (too busy lately...). It works great! Thanks!
